apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: clk588gvp-nodejs 
  janus-idp.io/tekton: clk588gvp-nodejs
  backstage.io/kubernetes-id: clk588gvp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: clk588gvp-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  