apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: clk588gvp-nodejs
  janus-idp.io/tekton: clk588gvp-nodejs
  backstage.io/kubernetes-id: clk588gvp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: clk588gvp-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
