apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: clk588gvp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clk588gvp-nodejs 
  name: clk588gvp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: clk588gvp-nodejs 
